// flow-typed signature: d72df9735d44e79876191eacbce8965a
// flow-typed version: <<STUB>>/json2md_v^1.5.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json2md'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'json2md' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json2md/dist/json2md.min' {
  declare module.exports: any;
}

declare module 'json2md/lib/converters' {
  declare module.exports: any;
}

declare module 'json2md/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json2md/dist/json2md.min.js' {
  declare module.exports: $Exports<'json2md/dist/json2md.min'>;
}
declare module 'json2md/lib/converters.js' {
  declare module.exports: $Exports<'json2md/lib/converters'>;
}
declare module 'json2md/lib/index.js' {
  declare module.exports: $Exports<'json2md/lib/index'>;
}
