// flow-typed signature: f1e10f7132275a2ec6054b1929ad0fb5
// flow-typed version: <<STUB>>/phantom_v^2.1.12/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phantom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'phantom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phantom/lib/command' {
  declare module.exports: any;
}

declare module 'phantom/lib/function_bind_polyfill' {
  declare module.exports: any;
}

declare module 'phantom/lib/index' {
  declare module.exports: any;
}

declare module 'phantom/lib/out_object' {
  declare module.exports: any;
}

declare module 'phantom/lib/page' {
  declare module.exports: any;
}

declare module 'phantom/lib/phantom' {
  declare module.exports: any;
}

declare module 'phantom/lib/shim' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phantom/lib/command.js' {
  declare module.exports: $Exports<'phantom/lib/command'>;
}
declare module 'phantom/lib/function_bind_polyfill.js' {
  declare module.exports: $Exports<'phantom/lib/function_bind_polyfill'>;
}
declare module 'phantom/lib/index.js' {
  declare module.exports: $Exports<'phantom/lib/index'>;
}
declare module 'phantom/lib/out_object.js' {
  declare module.exports: $Exports<'phantom/lib/out_object'>;
}
declare module 'phantom/lib/page.js' {
  declare module.exports: $Exports<'phantom/lib/page'>;
}
declare module 'phantom/lib/phantom.js' {
  declare module.exports: $Exports<'phantom/lib/phantom'>;
}
declare module 'phantom/lib/shim.js' {
  declare module.exports: $Exports<'phantom/lib/shim'>;
}
