module.exports = [
  'Open Sans',
  'Roboto',
  'Lato',
  'Oswald',
  'Roboto Condensed',
  'Source Sans Pro',
  'Source Serif Pro',
  'Montserrat',
  'Raleway',
  'PT Sans',
  'Lora',
  'Roboto Slab',
  'Open Sans Condensed',
  'Ubuntu',
  'Merriweather',
  'Arimo',
  'PT Sans Narrow',
  'Noto Sans',
  'Titillium Web',
  'PT Serif',
  'Playfair Display',
  'Fjalla One',
  'Bitter',
  'Muli',
  'Oxygen',
  'Inconsolata',
  'Dosis',
  'Hind',
  'Cabin',
  'Lobster',
  'Yanone Kaffeesatz',
  'Noto Serif',
  'Arvo',
  'Poiret One',
  'Nunito',
  'Bree Serif',
  'Merriweather Sans',
  'Poppins',
  'Alegreya Sans',
  'Abel',
  'Josefin Sans',
  'Libre Baskerville',
  'Asap',
  'Exo 2',
  'Anton',
  'Ubuntu Condensed',
  'Pacifico',
  'Archivo Narrow',
  'Crimson Text',
  'Candal',
  'Francois One',
  'Varela Round',
  'Quicksand',
  'Play',
  'Shadows Into Light',
  'Vollkorn',
  'Signika',
  'Passion One',
  'Cuprum',
  'Orbitron',
  'Questrial',
  'Karla',
  'Catamaran',
  'Maven Pro',
  'Alegreya',
  'Alegreya SC',
  'PT Sans Caption',
  'Exo',
  'Dancing Script',
  'Amatic SC',
  'Rokkitt',
  'Pathway Gothic One',
  'Rubik',
  'Abril Fatface',
  'Yellowtail',
  'Fira Sans',
  'Architects Daughter',
  'Hammersmith One',
  'Patua One',
  'Roboto Mono',
  'Righteous',
  'Monda',
  'Cinzel',
  'Crete Round',
  'EB Garamond',
  'Noticia Text',
  'Kaushan Script',
  'Sanchez',
  'Josefin Slab',
  'Acme',
  'Russo One',
  'Lobster Two',
  'Comfortaa',
  'Ropa Sans',
  'ABeeZee',
  'Quattrocento Sans',
  'Domine',
  'Work Sans',
  'Cormorant Garamond',
  'Libre Franklin',
  'Space Mono',
  'Eczar',
  'BioRhyme',
  'Chivo',
  'Old Standard TT',
  'Rajdhani',
  'Cardo',
  'Gentium Basic',
  'Neuton',
  'Anonymous Pro',
]

